# Generated by Django 4.1.2 on 2024-03-19 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('country_code', models.CharField(max_length=3)),
                ('income_group', models.CharField(choices=[('Low Income', 'Low Income'), ('Lower Middle Income', 'Lower Middle Income'), ('Upper Middle Income', 'Upper Middle Income'), ('High Income', 'High Income')], max_length=20)),
                ('years', models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)])),
                ('special_notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='IncomeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Low income', 'Low income'), ('Lower middle income', 'Lower middle income'), ('Upper middle income', 'Upper middle income'), ('High income', 'High income'), ('No group', 'No group')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Latin America & Caribbean', 'Latin America & Caribbean'), ('South Asia', 'South Asia'), ('Sub-Saharan Africa', 'Sub-Saharan Africa'), ('Europe & Central Asia', 'Europe & Central Asia'), ('Middle East & North Africa', 'Middle East & North Africa'), ('East Asia & Pacific', 'East Asia & Pacific'), ('North America', 'North America'), ('No region', 'No region')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='RegionCountries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RuralPopulationApp.region')),
            ],
        ),
        migrations.CreateModel(
            name='IncomeCountries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RuralPopulationApp.incomegroup')),
            ],
        ),
    ]
