# Generated by Django 4.1.2 on 2024-03-19 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RuralPopulationApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='country',
            name='income_group',
            field=models.CharField(choices=[('Low Income', 'Low Income'), ('Lower Middle Income', 'Lower Middle Income'), ('Upper Middle Income', 'Upper Middle Income'), ('High Income', 'High Income'), ('No region', 'No region')], max_length=20),
        ),
    ]
