# Generated by Django 4.1.2 on 2024-03-19 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RuralPopulationApp', '0002_country_value_alter_country_income_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
