# Generated by Django 4.1.2 on 2024-03-19 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RuralPopulationApp', '0003_alter_country_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='value',
        ),
        migrations.RemoveField(
            model_name='country',
            name='years',
        ),
        migrations.AddField(
            model_name='country',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RuralPopulationApp.region'),
        ),
        migrations.AlterField(
            model_name='country',
            name='income_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RuralPopulationApp.incomegroup'),
        ),
        migrations.CreateModel(
            name='DataEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)])),
                ('value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RuralPopulationApp.country')),
            ],
        ),
    ]
